import Foundation
import SaplingCore

/// Default-deny egress from job environments to private address space (§8).
///
/// Jobs run trusted-but-not-audited code on a machine that also hosts
/// deployment infrastructure, so the property that matters is: a job can
/// reach the internet, and nothing else on the LAN, the tailnet, or the
/// host's own services.
///
/// Enforcement is a pf anchor. macOS's Virtualization.framework NAT routes
/// both Tart VM traffic and Apple `container` traffic through the host's IP
/// stack via `bridge*` interfaces, so pf on the host is the one place that
/// sees all of it.
public struct NetworkGuard: Sendable {
    /// Name of the pf anchor Sapling's rules live in.
    public static let anchorName = "sapling"
    /// Where the anchor's rule file is written.
    public static let anchorPath = "/etc/pf.anchors/sapling"

    /// Everything a job must not reach.
    ///
    /// CGNAT space (100.64/10) is in here deliberately — that's Tailscale, and a
    /// job has no business talking to the tailnet.
    public static let defaultBlockedCIDRs = [
        "10.0.0.0/8",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "169.254.0.0/16",
        "100.64.0.0/10",
        "127.0.0.0/8",
    ]

    let config: NetworkConfig

    /// Creates a guard for the given network configuration.
    public init(config: NetworkConfig) {
        self.config = config
    }

    /// What was actually loaded into pf, for logging and diagnostics.
    public struct Applied: Sendable {
        /// Subnets job environments live on.
        public let jobSubnets: [String]
        /// Bridge gateway addresses, which stay reachable.
        public let gateways: [String]
        /// Ranges job environments are denied.
        public let blocked: [String]
        /// Ranges permitted despite the block rules.
        public let allowed: [String]
    }

    /// Build and load the anchor.
    ///
    /// Requires root, which the daemon has as a LaunchDaemon (§10).
    @discardableResult
    public func apply() async throws -> Applied {
        guard config.blockPrivateRanges else {
            throw NetworkGuardError.disabled
        }
        guard getuid() == 0 else {
            throw NetworkGuardError.notRoot
        }

        let interfaces = try await Self.discoverBridgeInterfaces()
        guard !interfaces.isEmpty else {
            throw NetworkGuardError.noJobNetworks
        }

        let jobSubnets = interfaces.map(\.subnet)
        let gateways = interfaces.map { "\($0.address)/32" }
        let blocked = Self.defaultBlockedCIDRs + config.extraBlockedCIDRs
        // The bridge gateway has to stay reachable or the VM loses DHCP, DNS,
        // and the host cache proxy along with its internet access.
        let allowed = gateways + config.allowedCIDRs

        let rules = """
            # Generated by sapling \(SaplingVersion.current). Do not edit;
            # `sapling serve` rewrites this file on every start.
            table <sapling_jobnets> { \(jobSubnets.joined(separator: ", ")) }
            table <sapling_allowed> { \(allowed.joined(separator: ", ")) }
            table <sapling_blocked> { \(blocked.joined(separator: ", ")) }

            pass quick from <sapling_jobnets> to <sapling_allowed>
            block drop quick from <sapling_jobnets> to <sapling_blocked>

            """

        try rules.write(toFile: Self.anchorPath, atomically: true, encoding: .utf8)

        // pf may be disabled entirely on a fresh machine; -E enables it and
        // bumps a reference count, which is safe to call repeatedly.
        _ = try? await ProcessRunner.run("pfctl", ["-E"], timeout: .seconds(20))

        let load = try await ProcessRunner.run(
            "pfctl", ["-a", Self.anchorName, "-f", Self.anchorPath],
            timeout: .seconds(30)
        )
        guard load.succeeded else {
            throw NetworkGuardError.loadFailed(load.stderr.trimmingCharacters(in: .whitespacesAndNewlines))
        }

        return Applied(jobSubnets: jobSubnets, gateways: gateways, blocked: blocked, allowed: allowed)
    }

    /// Read back what pf actually has loaded, rather than trusting that our
    /// write succeeded. `sapling doctor` uses this.
    public static func verify() async -> (loaded: Bool, rules: [String]) {
        guard
            let result = try? await ProcessRunner.run(
                "pfctl", ["-a", anchorName, "-sr"], timeout: .seconds(20)),
            result.succeeded
        else {
            return (false, [])
        }
        let rules = result.stdout
            .split(separator: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
        // An anchor that exists but has no block rule is worse than none at
        // all, because it looks configured.
        let hasBlock = rules.contains { $0.hasPrefix("block") }
        return (hasBlock, rules)
    }

    /// Removes Sapling's rules from pf, leaving the anchor in place.
    public static func flush() async {
        _ = try? await ProcessRunner.run("pfctl", ["-a", anchorName, "-F", "rules"], timeout: .seconds(20))
    }

    // MARK: - Interface discovery

    /// A `bridge*` interface macOS created for VM networking.
    public struct BridgeInterface: Sendable {
        /// Interface name, for example `bridge100`.
        public let name: String
        /// The host's address on this bridge — the job environments' gateway.
        public let address: String
        /// Netmask as `ifconfig` reports it, in hex.
        public let netmask: String
        /// The network in CIDR form, which is what pf tables want.
        public let subnet: String
    }

    /// Find the `bridge*` interfaces macOS creates for VM networking.
    ///
    /// These are created on demand — the first Tart VM or container brings
    /// one up — so this is re-run each time the guard is applied rather than
    /// cached at startup.
    public static func discoverBridgeInterfaces() async throws -> [BridgeInterface] {
        let result = try await ProcessRunner.run("ifconfig", [], timeout: .seconds(20))
        guard result.succeeded else {
            throw NetworkGuardError.loadFailed("could not run ifconfig: \(result.stderr)")
        }
        return parseInterfaces(from: result.stdout)
    }

    /// Split out from the `ifconfig` call so the parsing can be exercised
    /// against real output containing bridges — a dev Mac has none, and the
    /// pf rules are only as correct as this.
    static func parseInterfaces(from output: String) -> [BridgeInterface] {
        var interfaces: [BridgeInterface] = []
        var currentName: String?

        for rawLine in output.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(rawLine)
            if !line.hasPrefix("\t") && !line.hasPrefix(" ") {
                currentName = line.split(separator: ":").first.map(String.init)
                continue
            }
            guard let name = currentName, name.hasPrefix("bridge") else { continue }

            // ifconfig indents continuation lines with a tab, so splitting
            // on spaces alone leaves "\tinet" and never matches.
            let fields = line.split(whereSeparator: \.isWhitespace).map(String.init)
            guard let inetIndex = fields.firstIndex(of: "inet"),
                inetIndex + 1 < fields.count,
                let maskIndex = fields.firstIndex(of: "netmask"),
                maskIndex + 1 < fields.count
            else { continue }

            let address = fields[inetIndex + 1]
            let maskHex = fields[maskIndex + 1]
            guard let prefix = prefixLength(fromHexNetmask: maskHex),
                let subnet = networkCIDR(address: address, prefix: prefix)
            else { continue }

            interfaces.append(
                BridgeInterface(
                    name: name,
                    address: address,
                    netmask: maskHex,
                    subnet: subnet
                ))
        }
        return interfaces
    }

    /// ifconfig prints netmasks as `0xffffff00`; pf wants a prefix length.
    static func prefixLength(fromHexNetmask hex: String) -> Int? {
        let cleaned = hex.hasPrefix("0x") ? String(hex.dropFirst(2)) : hex
        guard let value = UInt32(cleaned, radix: 16) else { return nil }
        return value.nonzeroBitCount
    }

    static func networkCIDR(address: String, prefix: Int) -> String? {
        let octets = address.split(separator: ".").compactMap { UInt32($0) }
        guard octets.count == 4 else { return nil }
        let packed = (octets[0] << 24) | (octets[1] << 16) | (octets[2] << 8) | octets[3]
        let mask: UInt32 = prefix == 0 ? 0 : ~UInt32(0) << (32 - prefix)
        let network = packed & mask
        return
            "\((network >> 24) & 0xFF).\((network >> 16) & 0xFF).\((network >> 8) & 0xFF).\(network & 0xFF)/\(prefix)"
    }
}

/// Why egress filtering could not be applied.
public enum NetworkGuardError: Error, LocalizedError, Sendable {
    case disabled
    case notRoot
    case noJobNetworks
    case loadFailed(String)

    /// An explanation naming the cause and, where there is one, the fix.
    public var errorDescription: String? {
        switch self {
        case .disabled:
            "network.block_private_ranges is off, so no egress filtering was applied"
        case .notRoot:
            "egress filtering needs root — run the daemon as a LaunchDaemon, not by hand"
        case .noJobNetworks:
            "no bridge interface found yet; it appears once the first VM or container starts"
        case .loadFailed(let detail):
            "could not load the pf anchor: \(detail)"
        }
    }
}
